name: Testing Go Code Base

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: Install dependencies
        run: |
          make dep
      - name: Build
        run: make build
      - name: Run Tests
        run: make test/cover
