name: Testing Go Code Base

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Run Tests
        run: go test ./... --cover
